---
- name: Install GNOME with LightDM on Ubuntu Server
  hosts: server   
  become: true
  vars:
    ansible_become_password: "{{ lookup('env', 'SUDO_PWD') | default('') }}"
  tasks:
    - name: Update APT cache
      apt:
        update_cache: yes

    - name: Upgrade all packages
      apt:
        upgrade: dist

    - name: Install GNOME
      apt:
        name: ubuntu-desktop
        state: present

    - name: Install LightDM display manager
      apt:
        name: lightdm
        state: present

    - name: Preconfigure LightDM as the default display manager
      debconf:
        name: lightdm
        question: shared/default-x-display-manager
        value: lightdm
        vtype: select

    - name: Reconfigure LightDM as default display manager
      command: dpkg-reconfigure lightdm
      args:
        creates: /etc/X11/default-display-manager
