---
- name: Install NoMachine for Remote accesss
  hosts: server
  become: true
  tasks:
    - name: Download NoMachine .deb package
      get_url:
        url: "https://download.nomachine.com/download/8.16/Linux/nomachine_8.16.1_1_amd64.deb"
        dest: "/tmp/nomachine.deb"
        mode: '0644'
    
    - name: Install NoMachine
      shell: dpkg -i /tmp/nomachine.deb
      args:
        executable: /bin/bash